Repository ComPWA/ampform, pull requests merged in 2021-07, with the labels that each got.

#93 ci: upgrade pinned requirements
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .cspell.json
  .pre-commit-config.yaml
  docs/extend_docstrings.py
Labels: 🖱️ DX

#94 ci: upgrade pinned requirements
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
Labels: 🖱️ DX

#95 docs!: describe helicity vs canonical
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .cspell.json
  docs/bibliography.bib
  docs/usage.md
  docs/usage/formalism.ipynb
  setup.cfg
Labels: 📝 Docs

#97 feat: define breakup_momentum
  docs/extend_docstrings.py
  src/ampform/dynamics/__init__.py
Labels: 💡 Feature

#98 phys: remove piecewise from rel. BW with ff
  .cspell.json
  commitlint.config.js
  docs/usage/dynamics.ipynb
  docs/usage/dynamics/analytic-continuation.ipynb
  src/ampform/dynamics/__init__.py
Labels: 📖 Physics

#99 ci: upgrade pinned requirements
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .pre-commit-config.yaml
Labels: 🖱️ DX

#101 ci: upgrade pinned requirements
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .pre-commit-config.yaml
  docs/conf.py
  docs/usage/interactive.ipynb
  src/symplot/__init__.py
Labels: 🖱️ DX

#100 docs: extend docstrings helicity and kinematics
  .flake8
  .pydocstyle
  docs/extend_docstrings.py
  src/ampform/helicity/__init__.py
  src/ampform/helicity/decay.py
  src/ampform/kinematics.py
Labels: ❔ Question, 📝 Docs

#103 docs: widen cell output where needed
  docs/extend_docstrings.py
  docs/usage/amplitude.ipynb
  docs/usage/dynamics.ipynb
  docs/usage/dynamics/analytic-continuation.ipynb
  docs/usage/dynamics/custom.ipynb
  docs/usage/dynamics/k-matrix.ipynb
  docs/usage/formalism.ipynb
  docs/usage/interactive.ipynb
  docs/usage/modify.ipynb
  docs/usage/symplot.ipynb
Labels: 📝 Docs

#106 fix: render DOT with figure, not sphinx.ext.graphviz
  .github/workflows/ci-docs.yml
  .github/workflows/linkcheck.yml
  docs/.gitignore
  docs/_images/.gitkeep
  docs/conf.py
  docs/extend_docstrings.py
  tox.ini
Labels: Bug, 📝 Docs

#107 ci!: switch to pre-commit.ci where possible
  .github/workflows/ci-style.yml
  .pre-commit-config.yaml
  README.md
  tox.ini
Labels: 🖱️ DX

#104 docs: ignore panel css to increase main content width
  docs/conf.py
  docs/usage/amplitude.ipynb
  docs/usage/dynamics.ipynb
  docs/usage/dynamics/analytic-continuation.ipynb
  docs/usage/dynamics/custom.ipynb
  docs/usage/dynamics/k-matrix.ipynb
  docs/usage/formalism.ipynb
  docs/usage/interactive.ipynb
  docs/usage/modify.ipynb
  pyproject.toml
Labels: 📝 Docs
