Repository ComPWA/ampform, pull requests merged in 2024-10, with the labels that each got.

#440 MAINT: drop Python 3.7 & 3.8 support due to EOL
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  docs/_extend_docstrings.py
  docs/conf.py
  docs/usage/dynamics/analytic-continuation.ipynb
  docs/usage/dynamics/k-matrix.ipynb
  docs/usage/helicity/spin-alignment.ipynb
  docs/usage/kinematics.ipynb
  pyproject.toml
  src/ampform/_qrules.py
  src/ampform/dynamics/builder.py
  src/ampform/dynamics/form_factor.py
  src/ampform/dynamics/kmatrix.py
  src/ampform/dynamics/phasespace.py
  src/ampform/helicity/__init__.py
  src/ampform/helicity/align/axisangle.py
  src/ampform/helicity/align/dpd.py
  src/ampform/helicity/decay.py
  src/ampform/helicity/naming.py
  src/ampform/io/__init__.py
  src/ampform/kinematics/__init__.py
  src/ampform/kinematics/angles.py
  src/ampform/kinematics/lorentz.py
  src/ampform/sympy/__init__.py
  src/ampform/sympy/_array_expressions.py
  src/ampform/sympy/_cache.py
  src/ampform/sympy/_decorator.py
  src/ampform/sympy/deprecated.py
  src/ampform/sympy/math.py
  src/symplot/__init__.py
  tests/helicity/test_angular_distributions.py
  tests/helicity/test_decay.py
  tests/symplot/test_symplot.py
  tests/sympy/test_cache.py
Labels: 🔨 Maintenance

#439 DX: define developer environment with `uv`
  .binder/apt.txt
  .binder/postBuild
  .binder/runtime.txt
  .constraints/.gitignore
  .constraints/py3.10.txt
  .constraints/py3.11.txt
  .constraints/py3.12.txt
  .constraints/py3.9.txt
  .cspell.json
  .editorconfig
  .envrc
  .gitattributes
  .github/workflows/benchmark.yml
  .github/workflows/cd.yml
  .github/workflows/ci-qrules-v0.9.yml
  .github/workflows/ci.yml
  .github/workflows/clean-caches.yml
  .github/workflows/lock.yml
  .github/workflows/pr-linting.yml
  .github/workflows/release-drafter.yml
  .gitignore
  .pre-commit-config.yaml
  .python-version
  .readthedocs.yml
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  docs/conf.py
  docs/index.md
  docs/install.md
  environment.yml
  pyproject.toml
  tox.ini
  uv.lock
Labels: 🔨 Maintenance, 🖱️ DX

#441 FIX: define dev dependencies as dependency groups
  .binder/postBuild
  .github/workflows/benchmark.yml
  .github/workflows/ci-qrules-v0.9.yml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  CONTRIBUTING.md
  docs/_extend_docstrings.py
  docs/install.md
  docs/usage/dynamics/analytic-continuation.ipynb
  docs/usage/dynamics/k-matrix.ipynb
  docs/usage/helicity/spin-alignment.ipynb
  docs/usage/kinematics.ipynb
  pyproject.toml
  src/ampform/dynamics/form_factor.py
  src/ampform/dynamics/kmatrix.py
  src/ampform/sympy/deprecated.py
  src/ampform/sympy/math.py
  src/symplot/__init__.py
  uv.lock
Labels: 🔨 Maintenance, 🖱️ DX, ⚠️ Interface
